### PR TITLE
Add async support for DSL

### PR DESCRIPTION
**Pull request by fornellas**
Add support for [TestSlide's DSL](https://testslide.readthedocs.io/en/1.7.0/testslide_dsl/index.html) to test async stuff.

Example usage:

```python
from testslide.dsl import context

@context
def testing_async_code(context):
  @context.around
  async def around(self, example):
    await example()  # Note that this must be awaited!

  @context.before
  async def before(self):
    pass

  @context.after
  async def after(self):
    pass

  @context.memoize_before
  async def memoize_before(self):
    return "memoize_before"

  @context.function
  async def function(self):
    return "function"

  @context.example
  async def example(self):
    assert self.memoize_before == "memoize_before"
    assert self.function == "function"
```

There's some ugliness at `_ExampleRunner`: `def _sync_run_all_hooks_and_example` and `async def _real_async_run_all_hooks_and_example` implement the exact same thing, one being sync the other async. I left big warnings at both to keep them in sync. Unfortunately I found no better way of sharing logic between sync and async code. I added a smoke test for the async version of the function, that should cover most of the ground to mitigate that.

Closes of #57 .

### CODE REVIEW

**Comment by jivid** [comment]
Hah I implemented a slightly different version of this in #60 just now :) Want to have a look at that approach and see how to proceed?

**Comment by fornellas** [comment]
@jivid I managed to make this work by either supporting all example and hook (before, after & around) code to be either sync or async. What do you think?

I'll update the PR with 3.6 fix, docs and test cases for failures when miking sync+async stuff, but this seems to cut it.

**Comment by fornellas** [comment]
Ready for review! Managed to make everything work with proper documentation.

**Comment by fornellas** [comment]
Closed by mistake, #68 reissues this.

**Pull request closed without merging**
